import { useState } from "react";
import { useLanguage } from "@/contexts/LanguageContext";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DisclaimerBanner } from "@/components/DisclaimerBanner";
import { useToast } from "@/hooks/use-toast";
import { 
  ArrowLeft, 
  ArrowRight, 
  Check, 
  Copy, 
  Download,
  TrendingUp,
  Zap,
  BarChart3,
  Settings
} from "lucide-react";
import { cn } from "@/lib/utils";

type Platform = "MT4" | "MT5" | null;
type Strategy = "trend_following" | "breakout" | "range" | "custom" | null;

interface RobotConfig {
  platform: Platform;
  strategy: Strategy;
  indicators: string[];
  timeframe: string;
  entryConditions: string;
  exitConditions: string;
  takeProfit: number;
  stopLoss: number;
  useTrailingStop: boolean;
  accountCurrency: string;
  lotSize: number;
  riskPercent: number;
  maxOpenTrades: number;
  tradingHours: string;
  robotName: string;
}

const RobotBuilder = () => {
  const { t, language } = useLanguage();
  const { toast } = useToast();
  
  const [step, setStep] = useState(1);
  const totalSteps = 5;
  
  const [config, setConfig] = useState<RobotConfig>({
    platform: null,
    strategy: null,
    indicators: [],
    timeframe: "H1",
    entryConditions: "",
    exitConditions: "",
    takeProfit: 50,
    stopLoss: 30,
    useTrailingStop: false,
    accountCurrency: "USD",
    lotSize: 0.1,
    riskPercent: 2,
    maxOpenTrades: 3,
    tradingHours: "00:00-23:59",
    robotName: "",
  });

  const updateConfig = <K extends keyof RobotConfig>(key: K, value: RobotConfig[K]) => {
    setConfig(prev => ({ ...prev, [key]: value }));
  };

  const canProceed = () => {
    switch (step) {
      case 1: return config.platform !== null;
      case 2: return config.strategy !== null;
      case 3: return config.entryConditions.length > 0;
      case 4: return config.lotSize > 0;
      case 5: return config.robotName.length > 0;
      default: return true;
    }
  };

  const generateCode = () => {
    const lang = config.platform === "MT4" ? "MQL4" : "MQL5";
    return `//+------------------------------------------------------------------+
//|                                        ${config.robotName}.${lang === "MQL4" ? "mq4" : "mq5"} |
//|                                        Generated by RobotTrader |
//|                                        Educational Example Only |
//+------------------------------------------------------------------+
#property copyright "RobotTrader - Educational Example"
#property link      "https://robottrader.app"
#property version   "1.00"
#property strict

// Input parameters
input double LotSize = ${config.lotSize};
input int TakeProfit = ${config.takeProfit};
input int StopLoss = ${config.stopLoss};
input bool UseTrailingStop = ${config.useTrailingStop ? "true" : "false"};
input int MaxTrades = ${config.maxOpenTrades};
input string TradingHours = "${config.tradingHours}";

// Strategy: ${config.strategy}
// Timeframe: ${config.timeframe}
// Entry conditions: ${config.entryConditions}
// Exit conditions: ${config.exitConditions}

//+------------------------------------------------------------------+
//| Expert initialization function                                     |
//+------------------------------------------------------------------+
int OnInit()
{
   Print("${config.robotName} initialized - Educational Example");
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                   |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   Print("${config.robotName} deinitialized");
}

//+------------------------------------------------------------------+
//| Expert tick function                                               |
//+------------------------------------------------------------------+
void OnTick()
{
   // TODO: Implement your strategy logic here
   // This is a template - customize based on your rules
   
   // Check trading hours
   if(!IsWithinTradingHours()) return;
   
   // Check max trades
   if(CountOpenTrades() >= MaxTrades) return;
   
   // Your entry logic here based on:
   // ${config.entryConditions}
   
   // Example: Check for entry signal
   if(CheckEntrySignal())
   {
      OpenTrade();
   }
   
   // Manage existing trades
   ManageTrades();
}

//+------------------------------------------------------------------+
//| Check if within trading hours                                      |
//+------------------------------------------------------------------+
bool IsWithinTradingHours()
{
   // Implement trading hours check
   return true;
}

//+------------------------------------------------------------------+
//| Count open trades                                                  |
//+------------------------------------------------------------------+
int CountOpenTrades()
{
   int count = 0;
   for(int i = OrdersTotal() - 1; i >= 0; i--)
   {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
      {
         if(OrderSymbol() == Symbol()) count++;
      }
   }
   return count;
}

//+------------------------------------------------------------------+
//| Check entry signal                                                 |
//+------------------------------------------------------------------+
bool CheckEntrySignal()
{
   // TODO: Implement your entry logic
   // Based on: ${config.entryConditions}
   return false;
}

//+------------------------------------------------------------------+
//| Open trade                                                         |
//+------------------------------------------------------------------+
void OpenTrade()
{
   // TODO: Implement order opening
   // Use LotSize, TakeProfit, StopLoss parameters
}

//+------------------------------------------------------------------+
//| Manage existing trades                                             |
//+------------------------------------------------------------------+
void ManageTrades()
{
   // TODO: Implement trade management
   // Exit conditions: ${config.exitConditions}
   // UseTrailingStop: ${config.useTrailingStop}
}

//+------------------------------------------------------------------+
// DISCLAIMER: This is an educational example only.
// Test thoroughly on demo accounts before any live trading.
// Past performance does not guarantee future results.
// Trading involves significant risk of loss.
//+------------------------------------------------------------------+
`;
  };

  const copyCode = () => {
    navigator.clipboard.writeText(generateCode());
    toast({
      title: t.builder.codeCopied,
    });
  };

  const downloadCode = () => {
    const code = generateCode();
    const extension = config.platform === "MT4" ? "mq4" : "mq5";
    const blob = new Blob([code], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${config.robotName || "MyRobot"}.${extension}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const saveRobot = () => {
    toast({
      title: t.builder.robotSaved,
    });
  };

  const strategies = [
    { 
      id: "trend_following" as const, 
      icon: TrendingUp, 
      title: t.builder.trendFollowing, 
      desc: t.builder.trendFollowingDesc 
    },
    { 
      id: "breakout" as const, 
      icon: Zap, 
      title: t.builder.breakout, 
      desc: t.builder.breakoutDesc 
    },
    { 
      id: "range" as const, 
      icon: BarChart3, 
      title: t.builder.rangeTrading, 
      desc: t.builder.rangeTradingDesc 
    },
    { 
      id: "custom" as const, 
      icon: Settings, 
      title: t.builder.custom, 
      desc: t.builder.customDesc 
    },
  ];

  const timeframes = ["M1", "M5", "M15", "M30", "H1", "H4", "D1", "W1"];
  const currencies = ["USD", "EUR", "GBP", "DKK", "SEK", "NOK"];

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar isAuthenticated onLogout={() => window.location.href = "/"} />

      <main className="flex-1 py-8">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <div className="mb-8 animate-fade-in">
            <h1 className="text-3xl font-bold text-foreground">{t.builder.title}</h1>
            <p className="text-muted-foreground mt-1">{t.builder.subtitle}</p>
          </div>

          {/* Progress */}
          <div className="mb-8">
            <div className="flex items-center justify-between text-sm text-muted-foreground mb-2">
              <span>{t.builder.step} {step} {t.builder.of} {totalSteps}</span>
              <span>{Math.round((step / totalSteps) * 100)}%</span>
            </div>
            <div className="h-2 bg-muted rounded-full overflow-hidden">
              <div 
                className="h-full bg-primary transition-all duration-300"
                style={{ width: `${(step / totalSteps) * 100}%` }}
              />
            </div>
          </div>

          {/* Step Content */}
          <div className="rounded-xl border border-border bg-card p-6 sm:p-8 card-shadow animate-fade-in">
            {/* Step 1: Platform */}
            {step === 1 && (
              <div>
                <h2 className="text-xl font-semibold text-foreground mb-2">{t.builder.step1Title}</h2>
                <p className="text-muted-foreground mb-6">{t.builder.step1Desc}</p>
                
                <div className="grid gap-4 sm:grid-cols-2">
                  {(["MT4", "MT5"] as const).map((platform) => (
                    <button
                      key={platform}
                      onClick={() => updateConfig("platform", platform)}
                      className={cn(
                        "rounded-xl border-2 p-6 text-left transition-all",
                        config.platform === platform
                          ? "border-primary bg-primary/5"
                          : "border-border hover:border-primary/50"
                      )}
                    >
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-lg font-semibold text-foreground">
                          {platform === "MT4" ? t.builder.mt4 : t.builder.mt5}
                        </span>
                        {config.platform === platform && (
                          <Check className="h-5 w-5 text-primary" />
                        )}
                      </div>
                      <p className="text-sm text-muted-foreground">
                        {platform === "MT4" ? t.builder.mt4Desc : t.builder.mt5Desc}
                      </p>
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Step 2: Strategy */}
            {step === 2 && (
              <div>
                <h2 className="text-xl font-semibold text-foreground mb-2">{t.builder.step2Title}</h2>
                <p className="text-muted-foreground mb-6">{t.builder.step2Desc}</p>
                
                <div className="grid gap-4 sm:grid-cols-2">
                  {strategies.map((s) => (
                    <button
                      key={s.id}
                      onClick={() => updateConfig("strategy", s.id)}
                      className={cn(
                        "rounded-xl border-2 p-6 text-left transition-all",
                        config.strategy === s.id
                          ? "border-primary bg-primary/5"
                          : "border-border hover:border-primary/50"
                      )}
                    >
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <s.icon className="h-5 w-5 text-primary" />
                          <span className="font-semibold text-foreground">{s.title}</span>
                        </div>
                        {config.strategy === s.id && (
                          <Check className="h-5 w-5 text-primary" />
                        )}
                      </div>
                      <p className="text-sm text-muted-foreground">{s.desc}</p>
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Step 3: Entry & Exit */}
            {step === 3 && (
              <div>
                <h2 className="text-xl font-semibold text-foreground mb-2">{t.builder.step3Title}</h2>
                <p className="text-muted-foreground mb-6">{t.builder.step3Desc}</p>
                
                <div className="space-y-6">
                  <div className="grid gap-4 sm:grid-cols-2">
                    <div className="space-y-2">
                      <Label>{t.builder.timeframe}</Label>
                      <Select value={config.timeframe} onValueChange={(v) => updateConfig("timeframe", v)}>
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {timeframes.map((tf) => (
                            <SelectItem key={tf} value={tf}>{tf}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <p className="text-xs text-muted-foreground">{t.builder.timeframeHelp}</p>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <Label>{t.builder.entryConditions}</Label>
                    <Textarea
                      value={config.entryConditions}
                      onChange={(e) => updateConfig("entryConditions", e.target.value)}
                      placeholder={language === "da" 
                        ? "F.eks. 'Køb når 20 MA krydser over 50 MA og RSI er under 70'" 
                        : "E.g. 'Buy when 20 MA crosses above 50 MA and RSI is below 70'"
                      }
                      rows={3}
                    />
                    <p className="text-xs text-muted-foreground">{t.builder.entryConditionsHelp}</p>
                  </div>

                  <div className="space-y-2">
                    <Label>{t.builder.exitConditions}</Label>
                    <Textarea
                      value={config.exitConditions}
                      onChange={(e) => updateConfig("exitConditions", e.target.value)}
                      placeholder={language === "da"
                        ? "F.eks. 'Luk når prisen rammer take profit eller stop loss'"
                        : "E.g. 'Close when price hits take profit or stop loss'"
                      }
                      rows={3}
                    />
                    <p className="text-xs text-muted-foreground">{t.builder.exitConditionsHelp}</p>
                  </div>

                  <div className="grid gap-4 sm:grid-cols-3">
                    <div className="space-y-2">
                      <Label>{t.builder.takeProfitPips}</Label>
                      <Input
                        type="number"
                        value={config.takeProfit}
                        onChange={(e) => updateConfig("takeProfit", Number(e.target.value))}
                      />
                    </div>
                    <div className="space-y-2">
                      <Label>{t.builder.stopLossPips}</Label>
                      <Input
                        type="number"
                        value={config.stopLoss}
                        onChange={(e) => updateConfig("stopLoss", Number(e.target.value))}
                      />
                    </div>
                    <div className="space-y-2">
                      <Label className="invisible">Trailing</Label>
                      <div className="flex items-center space-x-2 h-10">
                        <Checkbox
                          id="trailing"
                          checked={config.useTrailingStop}
                          onCheckedChange={(checked) => updateConfig("useTrailingStop", !!checked)}
                        />
                        <label htmlFor="trailing" className="text-sm">{t.builder.useTrailingStop}</label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Step 4: Risk Management */}
            {step === 4 && (
              <div>
                <h2 className="text-xl font-semibold text-foreground mb-2">{t.builder.step4Title}</h2>
                <p className="text-muted-foreground mb-6">{t.builder.step4Desc}</p>
                
                <div className="space-y-6">
                  <div className="grid gap-4 sm:grid-cols-2">
                    <div className="space-y-2">
                      <Label>{t.builder.accountCurrency}</Label>
                      <Select value={config.accountCurrency} onValueChange={(v) => updateConfig("accountCurrency", v)}>
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {currencies.map((c) => (
                            <SelectItem key={c} value={c}>{c}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-2">
                      <Label>{t.builder.lotSize}</Label>
                      <Input
                        type="number"
                        step="0.01"
                        value={config.lotSize}
                        onChange={(e) => updateConfig("lotSize", Number(e.target.value))}
                      />
                      <p className="text-xs text-muted-foreground">{t.builder.lotSizeHelp}</p>
                    </div>
                  </div>

                  <div className="grid gap-4 sm:grid-cols-2">
                    <div className="space-y-2">
                      <Label>{t.builder.riskPercent}</Label>
                      <Input
                        type="number"
                        step="0.5"
                        value={config.riskPercent}
                        onChange={(e) => updateConfig("riskPercent", Number(e.target.value))}
                      />
                      <p className="text-xs text-muted-foreground">{t.builder.riskPercentHelp}</p>
                    </div>
                    <div className="space-y-2">
                      <Label>{t.builder.maxOpenTrades}</Label>
                      <Input
                        type="number"
                        value={config.maxOpenTrades}
                        onChange={(e) => updateConfig("maxOpenTrades", Number(e.target.value))}
                      />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <Label>{t.builder.tradingHours}</Label>
                    <Input
                      value={config.tradingHours}
                      onChange={(e) => updateConfig("tradingHours", e.target.value)}
                      placeholder="00:00-23:59"
                    />
                    <p className="text-xs text-muted-foreground">{t.builder.tradingHoursHelp}</p>
                  </div>
                </div>
              </div>
            )}

            {/* Step 5: Summary & Generate */}
            {step === 5 && (
              <div>
                <h2 className="text-xl font-semibold text-foreground mb-2">{t.builder.step5Title}</h2>
                <p className="text-muted-foreground mb-6">{t.builder.step5Desc}</p>
                
                <div className="space-y-6">
                  <div className="space-y-2">
                    <Label>{t.builder.robotName}</Label>
                    <Input
                      value={config.robotName}
                      onChange={(e) => updateConfig("robotName", e.target.value)}
                      placeholder={t.builder.robotNamePlaceholder}
                    />
                  </div>

                  {/* Summary */}
                  <div className="rounded-lg bg-muted/50 p-4 space-y-2 text-sm">
                    <h3 className="font-medium text-foreground">{t.builder.summary}</h3>
                    <div className="grid gap-2 sm:grid-cols-2">
                      <div><span className="text-muted-foreground">{t.dashboard.platform}:</span> {config.platform}</div>
                      <div><span className="text-muted-foreground">{t.dashboard.strategy}:</span> {config.strategy}</div>
                      <div><span className="text-muted-foreground">{t.builder.timeframe}:</span> {config.timeframe}</div>
                      <div><span className="text-muted-foreground">{t.builder.lotSize}:</span> {config.lotSize}</div>
                      <div><span className="text-muted-foreground">TP:</span> {config.takeProfit} pips</div>
                      <div><span className="text-muted-foreground">SL:</span> {config.stopLoss} pips</div>
                    </div>
                  </div>

                  {/* Disclaimer */}
                  <DisclaimerBanner />

                  {/* Generated Code */}
                  {config.robotName && (
                    <div className="space-y-3">
                      <div className="flex items-center justify-between">
                        <h3 className="font-medium text-foreground">{t.builder.generatedCode}</h3>
                        <div className="flex gap-2">
                          <Button variant="outline" size="sm" onClick={copyCode}>
                            <Copy className="h-4 w-4 mr-1" />
                            {t.builder.copyCode}
                          </Button>
                          <Button variant="outline" size="sm" onClick={downloadCode}>
                            <Download className="h-4 w-4 mr-1" />
                            {t.builder.downloadCode}
                          </Button>
                        </div>
                      </div>
                      <pre className="rounded-lg bg-foreground/5 p-4 text-xs overflow-x-auto max-h-64">
                        <code>{generateCode()}</code>
                      </pre>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Navigation */}
            <div className="flex items-center justify-between mt-8 pt-6 border-t border-border">
              <Button
                variant="outline"
                onClick={() => setStep(s => s - 1)}
                disabled={step === 1}
              >
                <ArrowLeft className="h-4 w-4 mr-2" />
                {t.builder.previous}
              </Button>
              
              {step < totalSteps ? (
                <Button
                  onClick={() => setStep(s => s + 1)}
                  disabled={!canProceed()}
                >
                  {t.builder.next}
                  <ArrowRight className="h-4 w-4 ml-2" />
                </Button>
              ) : (
                <Button onClick={saveRobot} disabled={!canProceed()}>
                  <Check className="h-4 w-4 mr-2" />
                  {t.builder.saveRobot}
                </Button>
              )}
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default RobotBuilder;
